import { useTranslation } from 'react-i18next';
import type { Advantage } from '../../types';

export const Pages = {
  HOME: '/',
  STORE: '/store',
  AUTHORIZATION: '/authorization',
};

export const SwiperBreakpoints = {
  0: {
    slidesPerView: 1,
    centeredSlides: true,
  },
  480: {
    slidesPerView: 1.2,
    centeredSlides: true,
  },
  640: {
    slidesPerView: 2,
    centeredSlides: false,
  },
  768: {
    slidesPerView: 2.5,
    centeredSlides: false,
  },
  1024: {
    slidesPerView: 3,
    centeredSlides: false,
  },
  1280: {
    slidesPerView: 4,
    centeredSlides: false,
  },
  1536: {
    slidesPerView: 5,
    centeredSlides: false,
  },
};

export const useAdvantagesData = (): Advantage[] => {
  const { t } = useTranslation();

  return [
    {
      title: t('advantages.cards.prices.title'),
      text: t('advantages.cards.prices.text'),
    },
    {
      title: t('advantages.cards.fresh.title'),
      text: t('advantages.cards.fresh.text'),
    },
    {
      title: t('advantages.cards.florists.title'),
      text: t('advantages.cards.florists.text'),
    },
  ];
};

export const bestSellers = [
  {
    category: 'bestSellersBlock',
    id: 'bouquet1',
    title: 'bestSellersBlock.bouquet1.title',
    description: 'bestSellersBlock.bouquet1.description',
    price: 2150,
    image: '/images/image2.jpg',
    quantity: 1,
  },
  {
    category: 'bestSellersBlock',
    id: 'basket1',
    title: 'bestSellersBlock.basket1.title',
    description: 'bestSellersBlock.basket1.description',
    price: 3200,
    image: '/images/image3.jpg',
    quantity: 1,
  },
  {
    category: 'bestSellersBlock',
    id: 'aroma1',
    title: 'bestSellersBlock.aroma1.title',
    description: 'bestSellersBlock.aroma1.description',
    price: 1650,
    image: '/images/image4.jpg',
    quantity: 1,
  },
  {
    category: 'bestSellersBlock',
    id: 'roses1',
    title: 'bestSellersBlock.roses1.title',
    description: 'bestSellersBlock.roses1.description',
    price: 680,
    image: '/images/image5.jpg',
    quantity: 1,
  },
  {
    category: 'bestSellersBlock',
    id: 'bouquet2',
    title: 'bestSellersBlock.bouquet2.title',
    description: 'bestSellersBlock.bouquet2.description',
    price: 1450,
    image: '/images/image2.jpg',
    quantity: 1,
  },
  {
    category: 'bestSellersBlock',
    id: 'basket2',
    title: 'bestSellersBlock.basket2.title',
    description: 'bestSellersBlock.basket2.description',
    price: 1200,
    image: '/images/image3.jpg',
    quantity: 1,
  },
  {
    category: 'bestSellersBlock',
    id: 'aroma2',
    title: 'bestSellersBlock.aroma2.title',
    description: 'bestSellersBlock.aroma2.description',
    price: 900,
    image: '/images/image4.jpg',
    quantity: 1,
  },
  {
    category: 'bestSellersBlock',
    id: 'roses2',
    title: 'bestSellersBlock.roses2.title',
    description: 'bestSellersBlock.roses2.description',
    price: 1200,
    image: '/images/image5.jpg',
    quantity: 1,
  },
];

export const bouquets = [
  {
    category: 'bouquets',
    id: 'redRose',
    title: 'Красная роза',
    description: 'Красная роза с длинными стеблями',
    price: 740,
    image: '/images/image1.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'whiteLily',
    title: 'Белая лилия',
    description: 'Лилия с белыми лепестками и желтым центром',
    price: 1200,
    image: '/images/image2.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'colorfulTulips',
    title: 'Разноцветные тюльпаны',
    description: 'Тюльпаны разных цветов в букете',
    price: 430,
    image: '/images/image3.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'brightPinkRose',
    title: 'Ярко-розовая роза',
    description: 'Роза с ярко-розовыми лепестками',
    price: 640,
    image: '/images/image4.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'gentleWhiteLilies',
    title: 'Нежные белые лилии',
    description: 'Нежные белые лилии с зелеными листьями',
    price: 740,
    image: '/images/image5.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'springTulips',
    title: 'Весенние тюльпаны',
    description: 'Букет весенних тюльпанов с яркими цветами',
    price: 430,
    image: '/images/image2.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'miniRoses',
    title: 'Мини-розы',
    description: 'Красная роза с маленькими бутонами',
    price: 500,
    image: '/images/image4.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'exoticLily',
    title: 'Экзотическая лилия',
    description: 'Лилия с экзотическим ароматом и розовыми лепестками',
    price: 800,
    image: '/images/image2.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'purpleTulips',
    title: 'Фиолетовые тюльпаны',
    description: 'Тюльпаны с сочетанием белых и фиолетовых оттенков',
    price: 540,
    image: '/images/image3.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'deepRedRose',
    title: 'Насыщенная роза',
    description: 'Роза с насыщенным красным цветом и сильным ароматом',
    price: 660,
    image: '/images/image5.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'pinkTippedLily',
    title: 'Розовая лилия',
    description: 'Лилия с белыми лепестками и розовыми кончиками',
    price: 750,
    image: '/images/image2.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'orangeTulips',
    title: 'Оранжевые тюльпаны',
    description: 'Букет тюльпанов с желтыми и оранжевыми цветами',
    price: 850,
    image: '/images/image1.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'bushRose',
    title: 'Кустовая роза',
    description: 'Кустовая роза с множеством маленьких бутонов',
    price: 520,
    image: '/images/image1.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'creamLily',
    title: 'Кремовая лилия',
    description: 'Лилия с большими кремовыми лепестками',
    price: 650,
    image: '/images/image2.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'festiveTulips',
    title: 'Праздничные тюльпаны',
    description: 'Красочные тюльпаны в букете для особого случая',
    price: 540,
    image: '/images/image4.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'fieldDaisies',
    title: 'Полевые ромашки',
    description: 'Свежие только собраные с поля ромашки',
    price: 380,
    image: '/images/image1.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'dahlias',
    title: 'Георгины',
    description: 'Самые свежие так как собраны на ферме под Киевом',
    price: 400,
    image: '/images/image1.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'purpleTulips2',
    title: 'Фиолетовые тюльпаны',
    description: 'Тюльпаны с сочетанием белых и фиолетовых оттенков',
    price: 540,
    image: '/images/image3.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'deepRedRose2',
    title: 'Насыщенная роза',
    description: 'Роза с насыщенным красным цветом и сильным ароматом',
    price: 600,
    image: '/images/image5.jpg',
    quantity: 1,
  },
  {
    category: 'bouquets',
    id: 'pinkTippedLily2',
    title: 'Розовая лилия',
    description: 'Лилия с белыми лепестками и розовыми кончиками',
    price: 1290,
    image: '/images/image2.jpg',
    quantity: 1,
  },
];

export const plants = [
  {
    category: 'plants',
    id: 'ficus',
    title: 'plants.ficus.title',
    description: 'plants.ficus.description',
    price: 900,
    image: '/images/plant1.jpg',
    quantity: 1,
  },
  {
    category: 'plants',
    id: 'aloe',
    title: 'plants.aloe.title',
    description: 'plants.aloe.description',
    price: 345,
    image: '/images/plant2.jpg',
    quantity: 1,
  },
  {
    category: 'plants',
    id: 'kalanchoe',
    title: 'plants.kalanchoe.title',
    description: 'plants.kalanchoe.description',
    price: 450,
    image: '/images/plant3.jpg',
    quantity: 1,
  },
  {
    category: 'plants',
    id: 'spathiphyllum',
    title: 'plants.spathiphyllum.title',
    description: 'plants.spathiphyllum.description',
    price: 350,
    image: '/images/plant4.jpg',
    quantity: 1,
  },
  {
    category: 'plants',
    id: 'fern',
    title: 'plants.fern.title',
    description: 'plants.fern.description',
    price: 1200,
    image: '/images/plant5.jpg',
    quantity: 1,
  },
  {
    category: 'plants',
    id: 'croton',
    title: 'plants.croton.title',
    description: 'plants.croton.description',
    price: 450,
    image: '/images/plant3.jpg',
    quantity: 1,
  },
  {
    category: 'plants',
    id: 'sansevieria',
    title: 'plants.sansevieria.title',
    description: 'plants.sansevieria.description',
    price: 600,
    image: '/images/plant2.jpg',
    quantity: 1,
  },
  {
    category: 'plants',
    id: 'phalaenopsis',
    title: 'plants.phalaenopsis.title',
    description: 'plants.phalaenopsis.description',
    price: 700,
    image: '/images/plant5.jpg',
    quantity: 1,
  },
  {
    category: 'plants',
    id: 'zamioculcas',
    title: 'plants.zamioculcas.title',
    description: 'plants.zamioculcas.description',
    price: 515,
    image: '/images/plant1.jpg',
    quantity: 1,
  },
  {
    category: 'plants',
    id: 'dracaena',
    title: 'plants.dracaena.title',
    description: 'plants.dracaena.description',
    price: 465,
    image: '/images/plant3.jpg',
    quantity: 1,
  },
];

export const fruitBouquets = [
  {
    category: 'fruitBouquets',
    id: 'berryParadise',
    title: 'Ягодный рай',
    description: 'Набор свежих ягод: клубника, малина, черника и ежевика.',
    price: 1000,
    image: '/images/food1.jpg',
    quantity: 1,
  },
  {
    category: 'fruitBouquets',
    id: 'tropicalFantasy',
    title: 'Фантазия тропиков',
    description: 'Манго, ананас, киви и маракуйя в изысканном оформлении.',
    price: 1270,
    image: '/images/food2.jpg',
    quantity: 1,
  },
  {
    category: 'fruitBouquets',
    id: 'sunnyMix',
    title: 'Солнечный микс',
    description: 'Апельсины, мандарины, персики и виноград в ярком букете.',
    price: 650,
    image: '/images/food3.jpg',
    quantity: 1,
  },
  {
    category: 'fruitBouquets',
    id: 'cherryDelight',
    title: 'Вишневый восторг',
    description: 'Спелая вишня и черешня, дополненные декоративной зеленью.',
    price: 555,
    image: '/images/food4.jpg',
    quantity: 1,
  },
  {
    category: 'fruitBouquets',
    id: 'exoticParadise',
    title: 'Экзотический рай',
    description: 'Драгонфрукт, кокос, манго и ананас в стильной композиции.',
    price: 1010,
    image: '/images/food2.jpg',
    quantity: 1,
  },
  {
    category: 'fruitBouquets',
    id: 'strawberryParadise',
    title: 'Клубничный рай',
    description: 'Свежая клубника в сочетании с нежным шоколадным декором.',
    price: 1220,
    image: '/images/food1.jpg',
    quantity: 1,
  },
  {
    category: 'fruitBouquets',
    id: 'fruitFirework',
    title: 'Фруктовый фейерверк',
    description: 'Яркое сочетание арбуза, дыни, ананаса и киви.',
    price: 980,
    image: '/images/food4.jpg',
    quantity: 1,
  },
  {
    category: 'fruitBouquets',
    id: 'pomegranatePassion',
    title: 'Гранатовая страсть',
    description: 'Гранат, красные яблоки и виноград в элегантной упаковке.',
    price: 1150,
    image: '/images/food3.jpg',
    quantity: 1,
  },
];
